on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macOS-10.15', 'ubuntu-20.04' ]
        r:  [ devel ]

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.r }}

      - uses: s-u/R-actions/pkg-check@master
        with:
          debian-deps: libcurl4-openssl-dev
          check-flags: --as-cran
          
      - name: Show test output
        run: cd $BLDIR && cat osrv.Rcheck/tests/test.Rout

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.r }}-results
          path: ${{ env.BLDIR }}/osrv.Rcheck
